CASE_DATA = {
    "id": "CR-2026-004281",
    "title": "Affaire Martin — Enquête préliminaire",
    "status": "En cours",
    "priority": "Élevée",
    "type": "Enquête préliminaire",
    "jurisdiction": "Tribunal judiciaire de Paris",
    "opened_on": "12 septembre 2026",
    "last_activity": "Aujourd'hui, 09:42",
    "completion": 72,
    "deadline_count": 2,
    "missing_elements": 4,
    "pending_actions": 7,
    "demo_label": "Demo — données fictives",
    "demo_fictitious": True,
    "alerts": [
        {
            "id": "toxicology",
            "title": "Rapport toxicologique en retard",
            "description": "Demandé le 18/09/2026 — retard de 1 jour sur l'échéance prévue.",
            "severity": "critical",
            "target": "document",
            "related_document": "Rapport_Toxicologie.pdf",
        },
        {
            "id": "missing_photo",
            "title": "Pièce référencée mais absente",
            "description": "Le PV d'audition mentionne 'Photographie 17' mais elle n'est pas présente.",
            "severity": "high",
            "target": "document-intelligence",
            "related_document": "PV_Audition_03.pdf",
        },
        {
            "id": "deadline_72h",
            "title": "Délai procédural proche",
            "description": "La prochaine échéance critique est dans 72 heures.",
            "severity": "medium",
            "target": "deadline",
            "related_deadline": "Validation magistrat",
        },
    ],
    "intelligence": {
        "risk_level": "ÉLEVÉ",
        "reasoning": [
            {
                "title": "Rapport toxicologique en retard",
                "requested_on": "18/09/2026",
                "deadline": "03/10/2026",
                "delay_days": 1,
                "type": "delayed_report",
            },
            {
                "title": "Pièce référencée mais absente",
                "detail": "Le PV d'audition mentionne 'Photographie 17'. Aucun fichier correspondant détecté dans le dossier.",
                "type": "missing_reference",
            },
            {
                "title": "Délai procédural proche",
                "detail": "Prochaine échéance critique dans 72 heures.",
                "type": "deadline_risk",
            },
        ],
        "recommended_action": "Relancer le laboratoire médico-légal et vérifier la présence de la photographie 17 avant la prochaine échéance.",
        "blockage_chain": [
            "Dossier",
            "Expertise toxicologique",
            "Rapport non reçu",
            "Analyse des preuves impossible",
            "Validation parquet retardée",
        ],
        "blockage_main": "Rapport toxicologique non reçu.",
        "impact_estimated": "2 étapes dépendantes.",
        "responsible": "Médecin légiste.",
        "last_action": "Demande envoyée le 18/09/2026.",
        "next_action": "Préparer une relance.",
    },
    "timeline": [
        {
            "id": "signalement",
            "title": "Signalement",
            "status": "completed",
            "status_label": "✓",
            "responsible": "Police nationale",
            "start_date": "10/09/2026",
            "deadline": "12/09/2026",
            "required_documents": ["Plainte initiale"],
            "dependencies": ["Déclaration de la victime"],
            "blockers": [],
            "details": "Signalement enregistré et transmis au parquet.",
        },
        {
            "id": "ouverture_enquete",
            "title": "Ouverture de l'enquête",
            "status": "completed",
            "status_label": "✓",
            "responsible": "Procureur",
            "start_date": "12/09/2026",
            "deadline": "13/09/2026",
            "required_documents": ["Ordonnance d'ouverture"],
            "dependencies": ["Signalement"],
            "blockers": [],
            "details": "Ouverture validée et enquête formellement lancée.",
        },
        {
            "id": "auditions",
            "title": "Auditions",
            "status": "completed",
            "status_label": "✓",
            "responsible": "Enquêteur",
            "start_date": "14/09/2026",
            "deadline": "22/09/2026",
            "required_documents": ["PV d'audition"],
            "dependencies": ["Ouverture de l'enquête"],
            "blockers": [],
            "details": "Plusieurs auditions ont été menées et un fichier photo est référencé.",
        },
        {
            "id": "expertise_toxicologique",
            "title": "Expertise médico-légale",
            "status": "delayed",
            "status_label": "⚠",
            "responsible": "Médecin légiste",
            "start_date": "18/09/2026",
            "deadline": "03/10/2026",
            "required_documents": ["Rapport toxicologique"],
            "dependencies": ["Auditions", "Réquisition labo"],
            "blockers": ["Laboratoire retardé"],
            "details": "Le rapport est attendu mais n'est pas encore reçu. Le délai est désormais critique.",
        },
        {
            "id": "analyse_preuves",
            "title": "Analyse des preuves",
            "status": "in_progress",
            "status_label": "◐",
            "responsible": "Enquêteur",
            "start_date": "25/09/2026",
            "deadline": "05/10/2026",
            "required_documents": ["Preuves physiques", "Photographie 17"],
            "dependencies": ["Expertise médico-légale"],
            "blockers": ["Documentation incomplète"],
            "details": "Le traitement des éléments matériels est bloqué par la pièce manquante.",
        },
        {
            "id": "validation_parquet",
            "title": "Validation parquet",
            "status": "upcoming",
            "status_label": "○",
            "responsible": "Procureur",
            "start_date": "06/10/2026",
            "deadline": "09/10/2026",
            "required_documents": ["Synthèse du dossier"],
            "dependencies": ["Analyse des preuves"],
            "blockers": ["Expertise non finalisée"],
            "details": "Validation hiérarchique prévue après réception de l'ensemble des pièces.",
        },
        {
            "id": "orientation",
            "title": "Orientation",
            "status": "upcoming",
            "status_label": "○",
            "responsible": "Magistrat",
            "start_date": "10/10/2026",
            "deadline": "14/10/2026",
            "required_documents": ["Décision d'orientation"],
            "dependencies": ["Validation parquet"],
            "blockers": ["Délai de validation"],
            "details": "Le dossier attend la validation de l'étape précédente pour l'orientation finale.",
        },
    ],
    "actors": [
        {
            "name": "Magistrat",
            "person": "Marie Dupont",
            "status": "2 actions requises",
            "status_kind": "warning",
            "visibility": ["Magistrat", "Procureur", "Greffe"],
            "role_note": "Validation finale du dossier et cadrage des prochaines étapes.",
        },
        {
            "name": "Procureur",
            "person": "Thomas Bernard",
            "status": "En attente d'expertise",
            "status_kind": "neutral",
            "visibility": ["Procureur", "Magistrat"],
            "role_note": "Demande de validation des éléments essentiels et des pièces requises.",
        },
        {
            "name": "Enquêteur",
            "person": "Capitaine Martin",
            "status": "1 pièce manquante",
            "status_kind": "danger",
            "visibility": ["Enquêteur", "Procureur"],
            "role_note": "Le dossier présente une absence critique de preuve documentaire.",
        },
        {
            "name": "Médecin légiste",
            "person": "Dr. Claire Robert",
            "status": "Rapport en retard",
            "status_kind": "warning",
            "visibility": ["Médecin légiste", "Magistrat"],
            "role_note": "L'analyse toxicologique est la dépendance principale du dossier.",
        },
        {
            "name": "Avocat",
            "person": "Me Sophie Laurent",
            "status": "Nouvelle pièce disponible",
            "status_kind": "success",
            "visibility": ["Avocat", "Greffe"],
            "role_note": "Une pièce a été transmise et doit être vérifiée pour le dossier.",
        },
        {
            "name": "Greffe",
            "person": "Greffe",
            "status": "Aucune action",
            "status_kind": "success",
            "visibility": ["Greffe", "Magistrat"],
            "role_note": "Suivi des formalités et préparation des convocations.",
        },
    ],
    "documents": [
        {
            "document": "PV_Audition_03.pdf",
            "type": "PV d'audition",
            "date": "18/09/2026",
            "author": "Enquêteur",
            "status": "✓ Vérifié",
            "analysis": "Vérifié",
            "source": "PV d'audition pour le dossier.",
        },
        {
            "document": "Rapport_Toxicologie.pdf",
            "type": "Expertise",
            "date": "03/10/2026",
            "author": "Médecin légiste",
            "status": "⚠ En attente",
            "analysis": "À examiner",
            "source": "Demande envoyée le 18/09/2026.",
        },
        {
            "document": "Photo_17.jpg",
            "type": "Preuve",
            "date": "—",
            "author": "—",
            "status": "🔴 Manquante",
            "analysis": "Manquant",
            "source": "Référence détectée dans le procès-verbal d'audition.",
        },
        {
            "document": "Requisition_Labo.pdf",
            "type": "Réquisition",
            "date": "18/09/2026",
            "author": "Procureur",
            "status": "✓ Vérifié",
            "analysis": "Référence détectée",
            "source": "Demande de laboratoire validée.",
        },
    ],
    "deadlines": [
        {
            "id": "deadline-72h",
            "label": "Validation magistrat",
            "status": "critical",
            "when": "Dans 72 h",
            "date": "07/10/2026",
            "responsible": "Magistrat",
            "dependency": "Rapport toxicologique reçu",
            "consequence": "Blocage potentialisé de l'orientation",
        },
        {
            "id": "deadline-5d",
            "label": "Transmission expertise",
            "status": "warning",
            "when": "Dans 5 jours",
            "date": "09/10/2026",
            "responsible": "Médecin légiste",
            "dependency": "Photo 17 récupérée",
            "consequence": "Retard sur l'analyse des preuves",
        },
        {
            "id": "deadline-11d",
            "label": "Notification partie",
            "status": "info",
            "when": "Dans 11 jours",
            "date": "15/10/2026",
            "responsible": "Greffe",
            "dependency": "Validation du parquet",
            "consequence": "Risque de délais de notification",
        },
        {
            "id": "deadline-finished",
            "label": "Demande laboratoire",
            "status": "done",
            "when": "Terminée",
            "date": "18/09/2026",
            "responsible": "Procureur",
            "dependency": "Réquisition validée",
            "consequence": "Sans effet direct",
        },
    ],
    "agents": [
        {
            "name": "Document Agent",
            "purpose": "Detect missing documents, extract metadata, identify references.",
            "status": "Active",
            "last_run": "09:30",
            "observations": 18,
            "recommendations": 4,
        },
        {
            "name": "Deadline Agent",
            "purpose": "Monitor procedural deadlines and pending actions.",
            "status": "Active",
            "last_run": "09:31",
            "observations": 27,
            "recommendations": 5,
        },
        {
            "name": "Evidence Agent",
            "purpose": "Cross-reference evidence, documents and references.",
            "status": "Active",
            "last_run": "09:32",
            "observations": 12,
            "recommendations": 2,
        },
        {
            "name": "Workflow Agent",
            "purpose": "Understand dependencies and identify the next procedural action.",
            "status": "Active",
            "last_run": "09:34",
            "observations": 21,
            "recommendations": 4,
        },
        {
            "name": "Notification Agent",
            "purpose": "Prepare reminders and notifications.",
            "status": "Human approval required",
            "last_run": "09:18",
            "observations": 9,
            "recommendations": 2,
        },
    ],
    "role_views": {
        "Magistrat": {
            "focus": "Validation et décision",
            "tasks": [
                "Valider la relance au laboratoire",
                "Confirmer la priorisation de l'expertise",
                "Examiner la prochaine décision d'orientation",
            ],
            "visible_actors": ["Magistrat", "Procureur", "Médecin légiste"],
        },
        "Procureur": {
            "focus": "Ordonnancement et demande",
            "tasks": [
                "Contrôler les pièces envoyées",
                "Suivre la demande de laboratoire",
                "Préparer la relance de l'expertise",
            ],
            "visible_actors": ["Procureur", "Enquêteur", "Médecin légiste"],
        },
        "Enquêteur": {
            "focus": "Investigation et pièces à compléter",
            "tasks": [
                "Rechercher la photographie 17",
                "Vérifier les références du PV d'audition",
                "Compléter la synthèse d'enquête",
            ],
            "visible_actors": ["Enquêteur", "Procureur", "Avocat"],
        },
        "Avocat": {
            "focus": "Consultation et pièces",
            "tasks": [
                "Vérifier la disponibilité de la nouvelle pièce",
                "Contrôler les dates de notification",
                "Préparer une demande de compléments",
            ],
            "visible_actors": ["Avocat", "Greffe", "Magistrat"],
        },
        "Médecin légiste": {
            "focus": "Expertise et délais scientifiques",
            "tasks": [
                "Confirmer l'échéance de l'analyse toxicologique",
                "Informuler du statut du rapport",
                "Identifier les éléments manquants",
            ],
            "visible_actors": ["Médecin légiste", "Procureur", "Magistrat"],
        },
        "Greffe": {
            "focus": "Formalités d'instruction",
            "tasks": [
                "Préparer la notification de partie",
                "Contrôler le calendrier interne",
                "Archiver les éléments validés",
            ],
            "visible_actors": ["Greffe", "Magistrat", "Procureur"],
        },
    },
}
